Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "xfce-ubuntu"
      vb.memory = 1024
      vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    (grep -q -E '^mesg n$' /root/.profile && sed -i 's/^mesg n$/tty -s \\&\\& mesg n/g' /root/.profile && echo 'Ignore the previous error about stdin not being a tty. Fixing it now...') || exit 0
    apt-get install python-software-properties --assume-yes
    add-apt-repository ppa:openjdk-r/ppa -y
    apt-get update
    apt-get install xubuntu-desktop --no-install-recommends --assume-yes
    apt-get install xubuntu-icon-theme --assume-yes
    apt-get install openjdk-8-jdk --assume-yes
    apt-get install git --assume-yes
    apt-get install firefox --assume-yes
    apt-get install nload --assume-yes
    dpkg-reconfigure lightdm
    reboot
  SHELL
end
