# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "java8-centos7"
    vb.memory = 512
    vb.cpus = 1
  end

  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.synced_folder "~", "/vagrant_data"
  
  config.vm.provision "shell", inline: <<-SHELL
    yum install java-1.8.0-openjdk-devel git -y
  SHELL
end
