# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "java8-centos7"
    vb.memory = 768
    vb.cpus = 1
  end

  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.synced_folder "~", "/vagrant_data"
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install epel-release java-1.8.0-openjdk-devel git net-tools nload psmisc -y
    groupadd docker
    usermod -aG docker vagrant 
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install docker-ce -y
    systemctl enable docker
    systemctl start docker
    curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  SHELL
end
