# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "xfce-precise64"
    vb.memory = 1024
    vb.cpus = 1
  end
  
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.synced_folder "~", "/vagrant_data"
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  config.vm.provision "shell", inline: <<-SHELL
    (grep -q -E '^mesg n$' /root/.profile && sed -i 's/^mesg n$/tty -s \\&\\& mesg n/g' /root/.profile && echo 'Ignore the previous error about stdin not being a tty. Fixing it now...') || exit 0
    apt-get update --fix-missing
    apt-get install python-software-properties --assume-yes
    add-apt-repository ppa:openjdk-r/ppa -y
    apt-get update --fix-missing
    apt-get install xubuntu-desktop --no-install-recommends --assume-yes
    apt-get install xubuntu-icon-theme --assume-yes
    apt-get install openjdk-8-jdk --assume-yes
    apt-get install git --assume-yes
    apt-get install firefox --assume-yes
    apt-get install nload --assume-yes
    dpkg-reconfigure lightdm
    reboot
  SHELL
end
